# Generated by Django 6.0.2 on 2026-02-18 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.ejemplar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='usuarios.socio')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_fin'], name='prestamos_p_fecha_f_a5c641_idx')],
            },
        ),
    ]
