# Generated by Django 6.0.2 on 2026-02-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_ejemplar_activo_titulo_catalogo_ti_isbn_ba3ff4_idx_and_more'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogo.ejemplar'),
        ),
    ]
