# Generated by Django 6.0.2 on 2026-02-18 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('BAJA', 'Baja lógica'), ('PRESTAMO', 'Registro préstamo'), ('DEVOLUCION', 'Registro devolución'), ('RESERVA', 'Registro reserva'), ('CANCELACION', 'Cancelación'), ('SANCION', 'Aplicación sanción'), ('LOGIN', 'Inicio sesión')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['fecha'], name='auditoria_a_fecha_54a243_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion'], name='auditoria_a_accion_a0755b_idx'),
        ),
    ]
