# Generated by Django 6.0.2 on 2026-02-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('RESERVADO', 'Reservado'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='catalogo.titulo')),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='catalogo_ej_estado_d1c04e_idx')],
            },
        ),
    ]
