# Generated by Django 6.0.2 on 2026-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=models.Index(fields=['isbn'], name='catalogo_ti_isbn_ba3ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=models.Index(fields=['titulo'], name='catalogo_ti_titulo_6b4f20_idx'),
        ),
        migrations.AddIndex(
            model_name='titulo',
            index=models.Index(fields=['autor'], name='catalogo_ti_autor_bb9d44_idx'),
        ),
    ]
