# Generated by Django 6.0.2 on 2026-02-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sancion',
            index=models.Index(fields=['fecha_fin'], name='sanciones_s_fecha_f_152dff_idx'),
        ),
        migrations.AddIndex(
            model_name='sancion',
            index=models.Index(fields=['activa'], name='sanciones_s_activa_72fb8e_idx'),
        ),
    ]
