# Generated by Django 6.0.2 on 2026-02-18 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.titulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='usuarios.socio')),
            ],
            options={
                'ordering': ['fecha_reserva'],
            },
        ),
    ]
